version: '3.7'

services:
  bash: &base
    build: .
    image: builder
    volumes:
      - .:/app
      # - dl:/app/buildroot/dl
      # - output:/app/buildroot/output
    working_dir: /app/buildroot
    command: bash
  
  # Theorically `BOARD_NAME=raspberrypi3_64 docker-compose run build`
  builder: &generate_image
    <<: *base
    command: 
      - /bin/bash
      - -c
      - |
        make BR2_EXTERNAL="/app/uxplay" O=output/$${BOARD_NAME} $${BOARD_NAME}_defconfig 
        cd output/$${BOARD_NAME} && make 
        mkdir -p /app/images/
        xz -c images/sdcard.img > /app/images/sdcard-$${BOARD_NAME}.img.xz
    # environment:
    #   - BOARD_NAME=${BOARD_NAME}
  
  # dtoverlay=vc4-kms-v3d
  rpi3:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi3_64
      - CONSOLE=false

  rpi0w:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi0w
      - CONSOLE=true
  
  # qemu-system-x86_64 -M pc -kernel bzImage -drive file=rootfs.ext2,if=virtio,format=raw -append "rootwait root=/dev/vda" -net nic,model=virtio -net user
  qemu:
    <<: *base
    command: 
      - /bin/bash
      - -c
      - |
        make BR2_EXTERNAL="/app/uxplay" O=output/qemu qemu_x86_64_defconfig 
        cd output/qemu && make

  pc:
    <<: *base
    command: 
      - /bin/bash
      - -c
      - |
        make BR2_EXTERNAL="/app/uxplay" O=output/pc pc_x86_64_bios_defconfig 
        cd output/pc && make
  
# volumes:
#   dl:
#   output:
