version: '3.7'

services:
  bash: &base
    build: .
    image: builder
    volumes:
      - .:/app
      # - dl:/app/buildroot/dl
      # - output:/app/buildroot/output
    working_dir: /app/buildroot
    command: bash
  
  # Theorically `BOARD_NAME=raspberrypi3_64 docker-compose run build`
  builder: &generate_image
    <<: *base
    command: 
      - /bin/bash
      - -c
      - |
        make BR2_EXTERNAL="/app/uxplay" O=output/$${BOARD_NAME} $${BOARD_NAME}_defconfig 
        cd output/$${BOARD_NAME} && make 
        mkdir -p /app/images/
        xz -c images/sdcard.img > /app/images/sdcard-$${BOARD_NAME}.img.xz
    # environment:
    #   - BOARD_NAME=${BOARD_NAME}
  
  # dtoverlay=vc4-kms-v3d
  rpi4:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi4_64

  rpi3:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi3_64

  rpi0w:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi0w
  
  rpi02w:
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypizero2w

