version: '3.7'

services:
  bash: &base
    build: .
    image: builder
    volumes:
      - .:/app
      # - dl:/app/buildroot/dl
      # - output:/app/buildroot/output
    working_dir: /app/buildroot
    command: bash
  
  generate_image_donotuse: &generate_image
    <<: *base
    command: bash -x -c "make BR2_EXTERNAL="/app/uxplay"  O=output/$${BOARD_NAME} $${BOARD_NAME}_defconfig && cd output/$${BOARD_NAME} && make && mkdir -p /app/images/ && cp images/sdcard.img /app/images/sdcard-$${BOARD_NAME}.img"
  
  build: # rpi3 for now
    <<: *generate_image
    environment:
      - BOARD_NAME=raspberrypi
  
  # -M pc -kernel bzImage -drive file=rootfs.ext2,if=virtio,format=raw -append "rootwait root=/dev/vda console=tty1 console=ttyS0"  -net nic,model=virtio -net user
  # --enable-sdl --with-sdlabi=2.0
  qemu:
    <<: *generate_image
    command: bash -x -c "make BR2_EXTERNAL="/app/uxplay"  O=output/qemu qemu_defconfig && cd output/qemu && make && mkdir -p /app/images/ && cp -r images /app/images/qemu"

# volumes:
#   dl:
#   output:
