name: Build-Single

on:
  workflow_dispatch:
    inputs:
      defconfig:
        type: choice
        description: Board
        options: 
        - raspberrypi0w
        - raspberrypizero2w
        #- raspberrypi4
        #- raspberrypi3a
        - raspberrypi3_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup config
      run: make BR2_EXTERNAL=../uxplay/ ${{ github.event.inputs.defconfig }}_defconfig
      working-directory: ./buildroot

    - name: Build
      run: make
      working-directory: ./buildroot

    - name: Compress sdcard.img
      run: xz -c sdcard.img > ${{ github.event.inputs.defconfig }}-sdcard.img.xz
      working-directory: ./buildroot/output/images

    - uses: actions/upload-artifact@v3
      with:
        name: UXPLAYBR
        path: ./buildroot/output/images/${{ github.event.inputs.defconfig }}-sdcard.img.xz
